### ISSUE TITLE
distribution includes both a Makefile.PL and Build.PL

### ISSUE THREAD

**Issue by karenetheridge** [hartzell/moox-strictconstructor#11]
Providing both files is generally not a good idea -- e.g. see http://neilb.org/2015/05/18/two-build-files-considered-harmful.html

Since you're building with Dist::Zilla and `[MakeMaker]` provides all the necessary functionality for this distribution, the best thing to do would be to drop the use of Module::Build entirely. It should only be used when the task is difficult or impossible to achieve with ExtUtils::MakeMaker.

**Comment by ppisar** [comment]
Moreover it adds dependency on both of the toolchains:

~~~
      "configure" : {
         "requires" : {
            "ExtUtils::MakeMaker" : "0",
            "Module::Build" : "0.28",
            "perl" : "5.004"
         }
      },
~~~

**Comment by karenetheridge** [comment]
Module::Build was dropped from core four years ago (it last appeared in the 5.20.* series), and the Perl Toolchain group discourages its use. It has some utility still in some distributions with very complicated compilation usecases, e.g. Alien::*, but even there work is being done to transition away from MB. For Dist::Zilla-managed distributions, it is a very simple matter to change the plugin being used and if Dist::Zilla can build the distribution, there should be no reason to stay with MB.

Also:  http://www.dagolden.com/index.php/2140/paying-respect-to-modulebuild/

**Comment by hartzell** [comment]
This will be fixed in the next release (I've updated the @HARTZELL plugin bundle).  Coming once I get @haarg's PR figured out.
