### ISSUE TITLE
Wrong minimal Perl dependency

### ISSUE THREAD

**Issue by ppisar** [hartzell/moox-strictconstructor#12]
META.json lists 5.004 perl as as configure dependency. But Makefile.PL  says 5.006. Please update the version string in the metadata.

**Comment by JJ** [comment]
Makefile.PL should be out anyway...

**Comment by hartzell** [comment]
@JJ -- @karenetheridge has convinced me that Makefile.PL is the way to go, so the Build.PL is out.

**Comment by hartzell** [comment]
@ppisa -- I'm not sure what to do here, those files are being generated by Dist::Zilla (the MinimumPerl plugin and the MakeMaker plugin respectively).  I suspect what's happening is that the MinimumPerl plugin is looking at *my* code and MakeMaker is coming along later and writing out a file that needs something a bit fancier.

I'm disinclined to hard code the version.

I'm open to suggestions.

**Comment by karenetheridge** [comment]
This should take care of itself once you create a new release with updated Dist::Zilla plugins.

**Comment by hartzell** [comment]
It doesn't.  I set up a tiny little distribution and built it with the Basic plugin and ended up with 5.004 in both places.  Same setup with my plugin got 5.004 in the metadata and 5.006 in the Makefile.PL.  Using the blunt hammer of commenting out halves of the code at a time, I discovered that the `Test::Compile` plugin causes the Makefile.PL to pick up the 5.006 requirement.  That plugin's metadata lists a requirement on 5.006 and the tests that it generates include `use 5.006;`.

This `dist.ini`:

```
name    = MinTest
author  = George Hartzell <hartzell@cpan.org>
license = Perl_5
copyright_holder = George Hartzell
main_module = lib/MinTest.pm
version = 1.0.0

[@Basic]
[Test::Compile]
[MinimumPerl]
```

and this `lib/MinTest.pm`:

```perl
package MinTest;

# ABSTRACT: turns baubles into trinkets

1;
```

will illustrate the problem.  I'll report it over at [the MinimumPerl plugin bug tracker](https://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-MinimumPerl`) and hardcode a minimum in my distro.

**Comment by hartzell** [comment]
Reported bug on the MinimumPerl tracker here: https://rt.cpan.org/Ticket/Display.html?id=124900

**Comment by karenetheridge** [comment]
FWIW, this isn't a bug. I've commented on the ticket.

**Comment by hartzell** [comment]
@karenetheridge's comment actually applies twice:

1. This bug report, against v0.008, wasn't correct, the module dependency is against 5.004 and/but the test dependency is against 5.006, as it should be.

2. The bug report I filed against the MinimumPerl plugin is also incorrect.  I'll close it.
