### ISSUE TITLE
[PRC] How may I be of help?

### ISSUE THREAD

**Issue by JJ** [hartzell/moox-strictconstructor#14]
I have been assigned this distribution for the Jan 2018 PR challenge. How may I help?

**Comment by hartzell** [comment]
Thoughts on #12?

**Comment by karenetheridge** [comment]
This distribution doesn't `dzil build` without errors, so that would be a good place to start. (Hint: if cpanfile is to stay in the git repository, it needs to be excluded from consideration by `[Git::GatherDir]`.)

**Comment by hartzell** [comment]
After today's commits it builds fine, the goal is to address all of the issues and PR's and then release.

I had two problems with the cpanfile, wasn't using the plugin and (now that you mention it) was excluding it from the repo.  Fixed (thanks!)
