### ISSUE TITLE
MooX::StrictConstructor doesn't work with namespace::clean

### ISSUE THREAD

**Issue by timbunce** [hartzell/moox-strictconstructor#3]
Adding `use namespace::clean;` after `use MooX::StrictConstructor;` breaks.
I noticed this by my attribute `default` clauses no longer working.

If you add   `use namespace::clean;` after `use MooX::StrictConstructor;` in t/basic.t (e.g., [here](https://metacpan.org/source/HARTZELL/MooX-StrictConstructor-0.006/t/basic.t#L27)) the test fails with
```
t/basic.t ....... 1/?
#   Failed test 'strict constructor blows up on unknown params'
#   at t/basic.t line 116.
#                   undef
#     doesn't match '(?-xism:unknown attribute.+: bad)'

#   Failed test 'subclass constructor handles known attributes correctly'
#   at t/basic.t line 121.
#          got: 'Found unknown attribute(s) passed to the constructor: thing at (eval 50) line 54.
# '
#     expected: undef

#   Failed test 'subclass that doesn't use strict correctly recognizes bad attribute'
#   at t/basic.t line 136.
#                   undef
#     doesn't match '(?-xism:unknown attribute.+: bad)'
# Looks like you failed 3 tests of 14.
```

**Comment by timbunce** [comment]
Same for `use namespace::clean -except => 'meta';`

**Comment by timbunce** [comment]
I added some logging to `namespace::clean` to see what it was going to 'clean' and compares what it said with and without MooX::StrictConstructor. The only difference was that with MooX::StrictConstructor loaded the list of things to clean included `new`!

Sure enough, using `use namespace::clean -except => ['new','meta'];` in the test made it pass.

**Comment by timbunce** [comment]
Per @haarg, using MooX::StrictConstructor _after_ namespace::clean works.
Would be nice for this to be documented somewhere.

**Comment by hartzell** [comment]
Tim, quick check: are you comfortable that documenting this interaction is sufficient, or do you think that somehow the module should magically work with/around namespace::clean (wording chosen to expose my bias...)

**Comment by timbunce** [comment]
A clear doc change seems fine to me. Thanks!

**Comment by hartzell** [comment]
Thanks!
