### ISSUE TITLE
Broken when subclassing a Moose module

### ISSUE THREAD

**Issue by pwr22** [hartzell/moox-strictconstructor#5]
The moo constructor will disallow allowed arguments from moose. Moose with MooseX::StrictConstructor subclassing Moo modules works fine

This is a major problem for interoperability and so unfortunately I think this should strongly discourage use of MooX::StrictConstructor

@haarg has suggested that it may be possible to detect and process Moose metadata to get the information needed to properly handle the situation.

**Comment by hartzell** [comment]
I'd be happy to see a pull request, or a description of how to go about grubbing about in some parental moose metadata.  Wonder how ugly it'd get?

It's worth documenting in any case.

I tend to use Moo when I'm avoiding Moose, which I guess is why I haven't run into it.  Hardly seems like it makes the package useless....

**Comment by pwr22** [comment]
I think my wording above comes across more strongly than I meant it. I wrote what I did because it can lead to confusing broken functionality when sub-classing something which itself does work

**Comment by hartzell** [comment]
I added this:

> A class that inherits from a L<Moose> based class will discover that the
L<Moose> class's attributes are disallowed.  Given sufficient L<Moose> meta
knowledge it might be possible to work around this.  I'd appreciate pull
requests and or an outline of a solution.

To the BUGS/ODDITIES section.  Does that seem correct and sufficient?
