### ISSUE TITLE
Fails to install if "strictures" module is missing

### ISSUE THREAD

**Issue by boftx** [hartzell/moox-strictconstructor#7]
Here is the output from trying an install on CentOS 5 (Perl 5.8.9) without strictures being present already.
However, when I ran perl Build.PL, followed by "Build installdeps" all went well. Thoughts?

<pre>
cpan> install MooX::StrictConstructor
CPAN: Storable loaded ok
Going to read /root/.cpan/Metadata
  Database was generated on Thu, 16 Apr 2015 09:41:02 GMT
Running install for module MooX::StrictConstructor
Running make for H/HA/HARTZELL/MooX-StrictConstructor-0.006.tar.gz
CPAN: Digest::MD5 loaded ok
CPAN: Compress::Zlib loaded ok
Checksum for /root/.cpan/sources/authors/id/H/HA/HARTZELL/MooX-StrictConstructor-0.006.tar.gz ok
Scanning cache /root/.cpan/build for sizes
Deleting from cache: /root/.cpan/build/bareword-filehandles-0.003 (10.7>10.0 MB)
Deleting from cache: /root/.cpan/build/multidimensional-0.011 (10.5>10.0 MB)
Deleting from cache: /root/.cpan/build/Perl-OSType-1.008 (10.5>10.0 MB)
Deleting from cache: /root/.cpan/build/PathTools-3.47 (10.3>10.0 MB)
MooX-StrictConstructor-0.006
MooX-StrictConstructor-0.006/README
MooX-StrictConstructor-0.006/Changes
MooX-StrictConstructor-0.006/LICENSE
MooX-StrictConstructor-0.006/dist.ini
MooX-StrictConstructor-0.006/META.yml
MooX-StrictConstructor-0.006/MANIFEST
MooX-StrictConstructor-0.006/Build.PL
MooX-StrictConstructor-0.006/t
MooX-StrictConstructor-0.006/t/basic.t
MooX-StrictConstructor-0.006/META.json
MooX-StrictConstructor-0.006/perlcritic.rc
MooX-StrictConstructor-0.006/t/00-compile.t
MooX-StrictConstructor-0.006/xt/author
MooX-StrictConstructor-0.006/xt/author/critic.t
MooX-StrictConstructor-0.006/xt/author/pod-spell.t
MooX-StrictConstructor-0.006/xt/release
MooX-StrictConstructor-0.006/xt/release/distmeta.t
MooX-StrictConstructor-0.006/xt/release/pod-syntax.t
MooX-StrictConstructor-0.006/xt/release/portability.t
MooX-StrictConstructor-0.006/xt/release/pod-coverage.t
MooX-StrictConstructor-0.006/xt/release/test-version.t
MooX-StrictConstructor-0.006/lib/MooX
/bin/tar: Read 8704 bytes from -
MooX-StrictConstructor-0.006/lib/MooX/StrictConstructor.pm
MooX-StrictConstructor-0.006/lib/Method/Generate/Constructor/Role
MooX-StrictConstructor-0.006/lib/Method/Generate/Constructor/Role/StrictConstructor.pm
Removing previously used /root/.cpan/build/MooX-StrictConstructor-0.006
Package seems to come without Makefile.PL.
  (The test -f "/root/.cpan/build/MooX-StrictConstructor-0.006/Makefile.PL" returned false.)
  Writing one on our own (setting NAME to MooXStrictConstructor)

  CPAN.pm: Going to build H/HA/HARTZELL/MooX-StrictConstructor-0.006.tar.gz

Checking if your kit is complete...
Looks good
Writing Makefile for MooXStrictConstructor
cp lib/MooX/StrictConstructor.pm blib/lib/MooX/StrictConstructor.pm
cp lib/Method/Generate/Constructor/Role/StrictConstructor.pm blib/lib/Method/Generate/Constructor/Role/StrictConstructor.pm
Manifying blib/man3/MooX::StrictConstructor.3pm
Manifying blib/man3/Method::Generate::Constructor::Role::StrictConstructor.3pm
  /usr/bin/make  -- OK
Running make test
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-compile.t .. 1/2 Can't locate strictures.pm in @INC (@INC contains: lib /root/.cpan/build/MooX-StrictConstructor-0.006/blib/lib /root/.cpan/build/MooX-StrictConstructor-0.006/blib/arch /usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.8.8 /usr/lib/perl5/site_perl /usr/lib64/perl5/vendor_perl/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.8.8 /usr/lib/perl5/vendor_perl /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/5.8.8 .) at lib/MooX/StrictConstructor.pm line 6.
BEGIN failed--compilation aborted at lib/MooX/StrictConstructor.pm line 6.
Compilation failed in require at -e line 1.

#   Failed test 'MooX::StrictConstructor loaded ok'
#   at t/00-compile.t line 62.
#                   ''
#     doesn't match '(?s-xim:^\s*MooX::StrictConstructor ok)'
# Looks like you failed 1 test of 2.
t/00-compile.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
t/basic.t ....... Can't locate strictures.pm in @INC (@INC contains: /root/.cpan/build/MooX-StrictConstructor-0.006/blib/lib /root/.cpan/build/MooX-StrictConstructor-0.006/blib/arch /usr/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.8.8 /usr/lib/perl5/site_perl /usr/lib64/perl5/vendor_perl/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.8.8 /usr/lib/perl5/vendor_perl /usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi /usr/lib/perl5/5.8.8 .) at /root/.cpan/build/MooX-StrictConstructor-0.006/blib/lib/MooX/StrictConstructor.pm line 6.
BEGIN failed--compilation aborted at /root/.cpan/build/MooX-StrictConstructor-0.006/blib/lib/MooX/StrictConstructor.pm line 6.
Compilation failed in require at t/basic.t line 26.
BEGIN failed--compilation aborted at t/basic.t line 26.
t/basic.t ....... Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 

Test Summary Report
-------------------
t/00-compile.t (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
t/basic.t     (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=2, Tests=2,  0 wallclock secs ( 0.02 usr  0.02 sys +  0.17 cusr  0.04 csys =  0.25 CPU)
Result: FAIL
Failed 2/2 test programs. 1/2 subtests failed.
make: *** [test_dynamic] Error 2
  /usr/bin/make test -- NOT OK
Running make install
  make test had returned bad status, won't install without force

cpan> 

</pre>

**Comment by boftx** [comment]
Forgot to add the CPAN version.
<pre>
cpan shell -- CPAN exploration and modules installation (v1.7602)
ReadLine support enabled
</pre>

**Comment by hartzell** [comment]
Hi boftx,

I'm confused and must admit that it's been a long time since I used a perl that old **or** the cpan tool.

`MooX::StrictConstructor` requires strictures, and has it listed in it's prerequisites in the Build.PL **and** the META.{json,yml}.  You were successful when you used the provided Build.PL

Looking through the transcript you provided I see that the cpan tool checked for a Makefile.PL, didn't find one, and decided to proceed by "Writing one of our own":

```
Package seems to come without Makefile.PL.
  (The test -f "/root/.cpan/build/MooX-StrictConstructor-0.006/Makefile.PL" returned false.)
  Writing one on our own (setting NAME to MooXStrictConstructor)
```

I suspect the `Makefile.PL` it created did not respect the prerequisites.

I don't know why `cpan` didn't use the provided `Build.PL`.

Can you install using `cpanm` instead?

**Comment by boftx** [comment]
From what I was told by others our version of CPAN.pm is too old to know about Build.PL and MakeMaker was too old to understand the meta files entirely. The question has become moot at this point as we are (finally) moving to a newer Perl, v5.14, in the (hopefully) near future.

Thank you for responding, I sure mine is an edge case that will go away eventually. That said, it appears that if the module had a Makefile.PL included the problem would be corrected even for very old Perls.

What is ironic is that Module::Builder is removed from CORE now.

Jim

**Comment by hartzell** [comment]
>Thank you for responding, I sure mine is an edge case that will go away eventually. That said, it appears that if the module had a Makefile.PL included the problem would be corrected even for very old Perls.

Are you really just about to switch, or is it worth me making a release that includes a Makefile.PL.  I'm not sure it's rational, but given the fact that the maintainer's trying to talk people out of using MakeMaker, I've tended to not include them.

g.

**Comment by boftx** [comment]
In theory we are switching soon, we already have on some deployments.

Switching away from MakeMaker makes no sense considering Module::Builder is no longer part of CORE as of 5.22. If it is not much trouble, then supplying one makes sense, just be aware that there is also now a large disconnect in what params MakeMaker will accept when considering very old ones and recent versions.

Overall, it might well be good enough to include some notes in the docs about this, telling people with very old Perls that if a normal CPAN install fails, then build manually with Build.PL instead.

Jim

**Comment by hartzell** [comment]
See if 0.007 works for you.  It has a Makefile.PL courtesy of Dist::Zilla::Plugin::MakeMaker.

**Comment by boftx** [comment]
Thanks!

I’ll see if I can get one of our SA types to either build me a VM so I have a clean environment or if they can try it themselves since they were the ones who had to make the RPM. This won’t happen until Monday at the earliest, possibly later depending on priorities.

Maybe I can just wipe strictures and MX::SC and re-install. I don’t think I upgraded my MakeMaker yet, and I know my CPAN.pm is still the original one.

Jim

**Comment by hartzell** [comment]
@boftx, let me know if this doesn't work for you.
